[WIP]ビューページの実装
sakurannn/chat-space pull request #2
Opened 2019-02-04 02:45 UTC by sakurannn

#WHAT
ルートパスのビューページを実装する。

#WHY
サービスに必須の機能であるため。

2019-02-09 12:34 UTC, TOMARUMARU reviewed
ファイルの最下行は改行いれましょう。いくつかのファイルで見られます。

インデントが深すぎるので全ファイル2スペースに統一しましょう

2019-02-09 12:34 UTC, TOMARUMARU commented on app/assets/stylesheets/application.scss
> +body{
application.scssはimportするだけのファイルにしたいですね

2019-02-09 12:34 UTC, TOMARUMARU commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-02-09 12:34 UTC, TOMARUMARU commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
ハッシュロケット修正しましょう

2019-02-09 13:29 UTC, sakurannn commented on app/assets/stylesheets/application.scss
> +body{
不要な記載を削除しました

2019-02-09 13:29 UTC, sakurannn commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
シンボル型へ修正しました

2019-02-09 13:29 UTC, sakurannn commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
シンボル型へ修正しました

2019-02-10 02:17 UTC, kuroko918 reviewed
stylesheet/fontawsomeディレクトリ以下のファイルは全てgemのfont-awsome-railsに含まれているので、消しておいてください！

2019-02-10 02:17 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> + *= require font-awesome
これは下でfontawsomeをimportしているので消してしまいましょう！

2019-02-10 02:17 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
font-awsomeではなく、font-awsome-railsですね！

2019-02-10 02:17 UTC, kuroko918 commented on app/assets/stylesheets/fontawesome/css/all.css
> +.fa,
font-awsomeはgemで入れているので、このファイルいらないです！

2019-02-10 02:17 UTC, kuroko918 commented on app/views/layouts/mailer.html.haml
> +!!!
mailerは使用しないので消しておきましょう！

2019-02-10 02:17 UTC, kuroko918 commented on app/views/layouts/mailer.text.haml
> += yield
こちらも同様にmailerは使用しないので消しておきましょう！

2019-02-10 02:31 UTC, sakurannn commented on app/assets/stylesheets/application.scss
> + *= require font-awesome
削除しました

2019-02-10 02:31 UTC, sakurannn commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
変更しました

2019-02-10 02:31 UTC, sakurannn commented on app/assets/stylesheets/fontawesome/css/all.css
> +.fa,
削除しました

2019-02-10 02:32 UTC, sakurannn commented on app/views/layouts/mailer.html.haml
> +!!!
削除しました

2019-02-10 02:32 UTC, sakurannn commented on app/views/layouts/mailer.text.haml
> += yield
削除しました

2019-02-10 02:36 UTC, kuroko918 commented on app/views/layouts/application.html.haml
> +    %link{rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.7.1/css/all.css", integrity: "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", crossorigin: "anony
10-11行目もfontawsomeはgemで入れているので消しましょう！

2019-02-10 02:36 UTC, kuroko918 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
不要なコメントは消しておきましょう！

2019-02-10 02:37 UTC, kuroko918 commented on app/views/layouts/application.html.haml
> +    %link{rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.7.1/css/all.css", integrity: "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", crossorigin: "anony
font-awsomeのアイコンが表示されなくなってしまったら、font-awsome-railsの書き方を調べて、アイコンのhtmlを変更して下さい。

2019-02-10 03:49 UTC, sakurannn commented on app/views/layouts/application.html.haml
> +    %link{rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.7.1/css/all.css", integrity: "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", crossorigin: "anony
不要な行は削除しました。

font-awsome-railsの書き方を調べたところ
application.scssにて@import "font-awesome";と記載するように
とあったので変更したところアイコンが表示されたのですが
この方法でよかったのでしょうか？

2019-02-10 03:49 UTC, sakurannn commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
削除しました。

2019-02-10 03:53 UTC, ghost requested changes

2019-02-10 03:53 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +@import "font-awesome";
こちらまだ変更されてないので、変更している場合はpushしてください

2019-02-10 03:53 UTC, hiroki5123 commented on app/assets/stylesheets/modules/_main.scss
> +    color: #333;
インデントずれてます

2019-02-10 03:53 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +      %a{href: "/"}
今の時点からlink_toで、仮置きしましょう

2019-02-10 04:17 UTC, sakurannn commented on app/views/messages/index.html.haml
> +      %a{href: "/"}
変更しました。

2019-02-10 04:17 UTC, sakurannn commented on app/assets/stylesheets/modules/_main.scss
> +    color: #333;
インデント修正しました。

@import "font-awesome";と変更したところアイコンが表示されませんでした。
font-awsome-railsの書き方を調べたところ
application.scssにて@import "font-awesome";と記載するように
とあったので変更したところアイコンが表示されたのですが、
この方法ではないということでしょうか？

2019-02-10 04:24 UTC, hiroki5123 commented on app/assets/stylesheets/modules/_main.scss
> +    color: #333;
もし正常に表示されてあるのであれば大丈夫です！

2019-02-10 04:24 UTC, ghost approved these changes
LGTMです！

2019-02-10 04:32 UTC, merged